export const A = `${import.meta.env.BASE_URL}fr`;
export const bag = (group: string, ...files: string[]) => files.map((file) => `${A}/bags/${group}/${file}.webp`);
export const drive = (...files: string[]) => files.map((file) => `${A}/drive/${file}.webp`);

export type Category = "Bags" | "Diamond Jewellery" | "Gemstone Jewellery" | "Scarves";
export type Product = {
  id: number; name: string; category: Category; material: string; price: number;
  colour: string; images: string[]; note: string;
  occasion: string[]; mood: string[]; palette: string[];
};

export const products: Product[] = [
  { id:1,name:"Apollo Crescent Suede Bag",category:"Bags",material:"Italian suede · Gold-tone studs",price:198,colour:"Tan",images:bag("apollo_02","01-08-2026-productshoot5356","01-08-2026-productshoot5357","01-08-2026-productshoot5361"),note:"Softly structured with an adjustable shoulder strap and hand-finished stud work.",occasion:["everyday","weekend","event"],mood:["relaxed","polished"],palette:["warm"] },

  { id:2,name:"Marlow Leather Hobo",category:"Bags",material:"Full-grain leather",price:229,colour:"Espresso",images:bag("apollo_01","01-08-2026-productshoot5323","01-08-2026-productshoot5326","01-08-2026-productshoot5337"),note:"A relaxed everyday shape, cut from full-grain leather that develops character with wear.",occasion:["everyday","work"],mood:["polished","minimal"],palette:["deep"] },
  { id:3,name:"Luna Suede Shoulder Bag",category:"Bags",material:"Brushed suede",price:189,colour:"Camel",images:bag("apollo_03","01-08-2026-productshoot5366","01-08-2026-productshoot5367","01-08-2026-productshoot5370"),note:"A compact curved silhouette with a tactile brushed finish and considered internal storage.",occasion:["weekend","event"],mood:["relaxed"],palette:["warm"] },
  { id:4,name:"Marlow Leather Backpack",category:"Bags",material:"Embossed full-grain leather",price:248,colour:"Chocolate",images:bag("apollo_11","01-08-2026-productshoot5484","01-08-2026-productshoot5492","01-08-2026-productshoot5500"),note:"A hands-free everyday shape with useful compartments and considered stitching.",occasion:["travel","work"],mood:["relaxed","minimal"],palette:["deep"] },
  { id:5,name:"Vela Woven Crossbody",category:"Bags",material:"Hand-woven leather",price:179,colour:"Black",images:bag("smart_07","01-08-2026-productshoot5394","01-08-2026-productshoot5396","01-08-2026-productshoot5402"),note:"Hand-woven panels bring quiet texture to a compact hands-free shape.",occasion:["everyday","travel"],mood:["minimal","polished"],palette:["deep"] },
  { id:6,name:"Noa Soft Leather Hobo",category:"Bags",material:"Supple leather",price:218,colour:"Black",images:bag("smart_08","01-08-2026-productshoot5435","01-08-2026-productshoot5440-1","01-08-2026-productshoot5447"),note:"An unstructured, softly draped bag designed to sit comfortably on the shoulder.",occasion:["everyday","work"],mood:["relaxed"],palette:["deep"] },
  { id:7,name:"Diamond Drop Hoops",category:"Diamond Jewellery",material:"Lab-grown diamonds · White metal",price:165,colour:"Silver",images:drive("lab-1","lab-4"),note:"A clean drop-hoop profile with a brilliant lab-grown diamond finish for everyday light.",occasion:["event","everyday"],mood:["polished"],palette:["neutral"] },
  { id:8,name:"Diamond Orbit Studs",category:"Diamond Jewellery",material:"Lab-grown diamonds · White metal",price:145,colour:"Silver",images:drive("lab-2","lab-1"),note:"Fine pavé circles frame a central lab-grown stone in a compact, easy-to-wear stud.",occasion:["work","everyday","gift"],mood:["minimal"],palette:["neutral"] },
  { id:9,name:"Diamond Line Hoops",category:"Diamond Jewellery",material:"Lab-grown diamonds · White metal",price:175,colour:"Silver",images:drive("lab-3","lab-2"),note:"A slender row of lab-grown stones brings a precise flash to a modern hoop.",occasion:["event","work"],mood:["polished"],palette:["neutral"] },
  { id:10,name:"Diamond Huggies",category:"Diamond Jewellery",material:"Lab-grown diamonds · White metal",price:155,colour:"Silver",images:drive("lab-4","lab-3"),note:"Close-fitting huggies finished with a single suspended lab-grown diamond.",occasion:["everyday","gift"],mood:["minimal"],palette:["neutral"] },
  { id:11,name:"Turquoise Charm Pendant",category:"Gemstone Jewellery",material:"Turquoise · Gold-tone setting",price:110,colour:"Gold",images:drive("gem-1","gem-2"),note:"A vivid turquoise centre set into an organically shaped gold-tone charm.",occasion:["event","everyday"],mood:["colourful","polished"],palette:["colour","warm"] },
  { id:12,name:"Rose Quartz Halo Pendant",category:"Gemstone Jewellery",material:"Rose quartz · Gold-tone setting",price:105,colour:"Gold",images:drive("gem-2","gem-3"),note:"Soft rose quartz is framed in a sculptural halo with a small light-catching accent.",occasion:["gift","event"],mood:["colourful","relaxed"],palette:["warm","colour"] },
  { id:13,name:"Moonstone Halo Pendant",category:"Gemstone Jewellery",material:"Moonstone · Gold-tone setting",price:108,colour:"Gold",images:drive("gem-3","gem-1"),note:"A luminous moonstone charm designed to show the natural variation of every stone.",occasion:["everyday","gift"],mood:["minimal","relaxed"],palette:["warm"] },
  { id:14,name:"Pearl Drop Huggies",category:"Gemstone Jewellery",material:"Freshwater pearl · Gold-tone hoop",price:98,colour:"Gold",images:drive("gem-4","gem-2"),note:"Baroque freshwater pearls bring an individual finish to polished everyday huggies.",occasion:["event","everyday"],mood:["polished"],palette:["warm","neutral"] },
  { id:15,name:"Merlot Cashmere Wrap",category:"Scarves",material:"Cashmere & merino wool · Soft fringe",price:95,colour:"Merlot",images:drive("scarf-1","scarf-2"),note:"A generous deep-red wrap with a fluid drape and softly finished fringe.",occasion:["everyday","work"],mood:["relaxed","colourful"],palette:["colour","deep"] },
  { id:16,name:"Ivory Everyday Scarf",category:"Scarves",material:"Cashmere & merino wool · Soft fringe",price:82,colour:"Ivory",images:drive("scarf-4","scarf-2"),note:"An easy neutral layer, light enough to drape and generous enough to wrap.",occasion:["everyday","event"],mood:["minimal","polished"],palette:["neutral"] },
  { id:17,name:"Midnight Merino Scarf",category:"Scarves",material:"Fine merino wool · Soft fringe",price:78,colour:"Navy",images:drive("scarf-3","scarf-1"),note:"A deep navy scarf with a smooth hand feel and useful everyday weight.",occasion:["work","travel"],mood:["polished","minimal"],palette:["deep"] },
  { id:18,name:"Oatmeal Cashmere Wrap",category:"Scarves",material:"Cashmere & merino wool · Woven finish",price:92,colour:"Oatmeal",images:drive("scarf-2","scarf-4"),note:"A close-woven neutral wrap that lets the material and finish lead.",occasion:["everyday","travel"],mood:["relaxed"],palette:["neutral","warm"] },
];
